import { useEffect, useState, useCallback } from "react";
import { Plus, UsersRound, BookOpen, MapPin, Layers, X, CheckCircle2, AlertCircle, Trash2, RefreshCw, Sparkles } from "lucide-react";
import "./catalog.css";
import { api } from "../lib/api";

const initialUser = { firstName: "", lastName: "", email: "", phone: "", role: "student", level: "", password: "" };

/**
 * Hook pour générer un code à partir d'un nom via l'API backend.
 * Retourne [code, setCode, isAutoGenerated, regenerate, isGenerating].
 */
function useCodeGenerator(type) {
  const [code, setCode] = useState("");
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [userEdited, setUserEdited] = useState(false);

  const generate = useCallback(async (name) => {
    if (!name || name.trim().length < 2) return;
    setIsGenerating(true);
    try {
      const res = await api.get(`/catalog/generate-code?type=${type}&name=${encodeURIComponent(name)}`);
      if (!userEdited) {
        setCode(res.code);
        setIsAutoGenerated(true);
      }
    } catch { /* silently fail */ }
    finally { setIsGenerating(false); }
  }, [type, userEdited]);

  const manualSet = useCallback((value) => {
    setCode(value);
    setUserEdited(true);
    setIsAutoGenerated(false);
  }, []);

  const regenerate = useCallback(async (name) => {
    setUserEdited(false);
    setIsGenerating(true);
    try {
      const res = await api.get(`/catalog/generate-code?type=${type}&name=${encodeURIComponent(name)}`);
      setCode(res.code);
      setIsAutoGenerated(true);
    } catch { /* silently fail */ }
    finally { setIsGenerating(false); }
  }, [type]);

  const reset = useCallback(() => {
    setCode("");
    setIsAutoGenerated(false);
    setUserEdited(false);
  }, []);

  return { code, setCode: manualSet, isAutoGenerated, generate, regenerate, isGenerating, reset };
}

export default function CatalogPage() {
  const [catalog, setCatalog] = useState({ levels: [], rooms: [], subjects: [], doctors: [] });
  const [users, setUsers] = useState([]);

  const [isFormOpen, setIsFormOpen] = useState(false);
  const [selectedType, setSelectedType] = useState("");

  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);

  const load = async () => {
    setCatalog(await api.get("/catalog"));
    try { setUsers(await api.get("/users")); } catch {}
  };

  useEffect(() => { load().catch((e) => setError(e.message)); }, []);

  const create = async (path, data) => {
    setError("");
    setMessage("");
    setLoading(true);
    try {
      await api.post(path, data);
      setMessage("Enregistrement réussi.");
      setIsFormOpen(false);
      load();
      setTimeout(() => setMessage(""), 4000);
    } catch (e) {
      setError(e.response?.data?.message || e.message || "Erreur lors de l'enregistrement.");
    } finally {
      setLoading(false);
    }
  };

  const remove = async (path) => {
    if (!window.confirm("Êtes-vous sûr de vouloir supprimer cet élément ?")) return;
    setError("");
    setMessage("");
    try {
      await api.delete(path);
      setMessage("Élément supprimé.");
      load();
      setTimeout(() => setMessage(""), 4000);
    } catch (e) {
      setError(e.response?.data?.message || e.message || "Erreur lors de la suppression.");
    }
  };

  const openForm = (type) => {
    setError("");
    setMessage("");
    setSelectedType(type);
    setIsFormOpen(true);
  };

  const options = [
    { id: 'level', label: 'Niveau', icon: Layers },
    { id: 'subject', label: 'Matière', icon: BookOpen },
    { id: 'room', label: 'Salle', icon: MapPin },
    { id: 'user', label: 'Utilisateur', icon: UsersRound }
  ];

  return (
    <div className="page catalog-page">
      <header className="page-header">
        <div>
          <p className="eyebrow">RÉFÉRENTIELS</p>
          <h1>Catalogue</h1>
          <p className="muted">Gérez les éléments fondamentaux réutilisables dans l'application.</p>
        </div>
        <div className="header-actions desktop-only">
          <button className="primary" onClick={() => openForm('level')}>
            <Plus size={16} /> Ajouter un élément
          </button>
        </div>
      </header>

      {message && <div className="alert success"><CheckCircle2 size={16}/> {message}</div>}
      {error && !isFormOpen && <div className="alert error"><AlertCircle size={16}/> {error}</div>}

      <div className="catalog-grid">
        <Resource title="Niveaux" icon={Layers} items={catalog.levels} onDelete={(id) => remove(`/catalog/levels/${id}`)} render={(x) => (<><strong>{x.name}</strong><span className="code-badge">{x.code}</span></>)} />
        <Resource title="Salles" icon={MapPin} items={catalog.rooms} onDelete={(id) => remove(`/catalog/rooms/${id}`)} render={(x) => (<><strong>{x.name}</strong><span className="code-badge">{x.code || x.location || "—"}</span></>)} />
        <Resource title="Matières" icon={BookOpen} items={catalog.subjects} onDelete={(id) => remove(`/catalog/subjects/${id}`)} render={(x) => (<><strong>{x.name}</strong><span className="code-badge">{x.code}</span></>)} />
      </div>

      <section className="card user-card">
        <div className="section-heading">
          <div>
            <p className="eyebrow">COMPTES</p>
            <h2>Utilisateurs</h2>
          </div>
          <UsersRound />
        </div>
        <div className="users-table">
          {users.map((u) => (
            <div key={u._id} className="user-row">
              <div className="avatar small">{u.firstName[0]}{u.lastName[0]}</div>
              <strong>{u.firstName} {u.lastName}</strong>
              <span>{u.email}</span>
              <span className="role-tag">{u.role}</span>
              <button className="delete-btn user-del-btn" onClick={() => remove(`/users/${u._id}`)} title="Supprimer"><Trash2 size={15} /></button>
            </div>
          ))}
          {!users.length && <p className="muted">Ajoutez les comptes de l'établissement.</p>}
        </div>
      </section>

      {/* Floating Action Button for Mobile */}
      <button className="fab mobile-only" onClick={() => openForm('level')} aria-label="Ajouter">
        <Plus size={24} />
      </button>

      {/* Dynamic Form Drawer/Modal */}
      <div className={`drawer-overlay ${isFormOpen ? 'open' : ''}`} onClick={() => setIsFormOpen(false)}></div>
      <aside className={`form-drawer ${isFormOpen ? 'open' : ''}`}>
        <header className="drawer-header">
          <h2>Création</h2>
          <button className="close-btn" onClick={() => setIsFormOpen(false)}><X size={20}/></button>
        </header>
        <div className="drawer-body">
          <div className="type-selector">
            <p className="field-label">Que souhaitez-vous enregistrer ?</p>
            <div className="type-options">
              {options.map(opt => (
                <button key={opt.id} className={`type-btn ${selectedType === opt.id ? 'active' : ''}`} onClick={() => setSelectedType(opt.id)}>
                  <opt.icon size={16} /> <span>{opt.label}</span>
                </button>
              ))}
            </div>
          </div>

          <div className="drawer-form-content">
            {error && isFormOpen && <div className="alert error"><AlertCircle size={16}/> {error}</div>}

            {selectedType === 'level' && (
              <CodeForm
                type="level"
                nameLabel="Nom du niveau"
                extraFields={[]}
                onSubmit={(data) => create("/catalog/levels", data)}
                loading={loading}
                key="level"
              />
            )}

            {selectedType === 'room' && (
              <CodeForm
                type="room"
                nameLabel="Nom de la salle"
                extraFields={[
                  ["location", "Localisation", "text", false],
                  ["capacity", "Capacité", "number", false]
                ]}
                onSubmit={(data) => create("/catalog/rooms", {
                  ...data,
                  capacity: data.capacity ? Number(data.capacity) : undefined
                })}
                loading={loading}
                key="room"
              />
            )}

            {selectedType === 'subject' && (
              <CodeForm
                type="subject"
                nameLabel="Nom de la matière"
                extraFields={[]}
                doctors={catalog.doctors}
                onSubmit={(data) => create("/catalog/subjects", data)}
                loading={loading}
                key="subject"
              />
            )}

            {selectedType === 'user' && (
              <UserForm levels={catalog.levels} onSubmit={(data) => create("/users", data)} loading={loading} />
            )}
          </div>
        </div>
      </aside>
    </div>
  );
}

/* ──────────────────────────────────────────────
   Composant CodeForm — avec génération auto du code
   ────────────────────────────────────────────── */
function CodeForm({ type, nameLabel, extraFields, doctors, onSubmit, loading }) {
  const [name, setName] = useState("");
  const [extras, setExtras] = useState({});
  const codeGen = useCodeGenerator(type);

  // Debounce : générer le code 500ms après la dernière frappe sur le nom
  useEffect(() => {
    if (name.trim().length < 2) return;
    const timer = setTimeout(() => codeGen.generate(name), 500);
    return () => clearTimeout(timer);
  }, [name]);

  const handleSubmit = (e) => {
    e.preventDefault();
    const data = { name, code: codeGen.code, ...extras };
    onSubmit(data);
    setName("");
    setExtras({});
    codeGen.reset();
  };

  const selectDoctors = (event) => setExtras({ ...extras, doctors: [...event.target.selectedOptions].map((option) => option.value) });

  return (
    <form className="dynamic-form" onSubmit={handleSubmit}>
      <div className="form-group">
        <label>{nameLabel} <span className="req">*</span></label>
        <input
          required
          placeholder={nameLabel}
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
      </div>

      <div className="form-group">
        <label>
          Code <span className="req">*</span>
          {codeGen.isAutoGenerated && (
            <span className="auto-badge"><Sparkles size={12} /> Auto</span>
          )}
        </label>
        <div className="code-input-wrap">
          <input
            required
            placeholder="Code généré automatiquement"
            value={codeGen.code}
            onChange={(e) => codeGen.setCode(e.target.value.toUpperCase())}
            className={codeGen.isAutoGenerated ? "auto-generated" : ""}
          />
          <button
            type="button"
            className="regen-btn"
            onClick={() => codeGen.regenerate(name)}
            disabled={codeGen.isGenerating || name.trim().length < 2}
            title="Régénérer le code"
          >
            <RefreshCw size={15} className={codeGen.isGenerating ? "spin" : ""} />
          </button>
        </div>
        {codeGen.isAutoGenerated && (
          <span className="code-hint">Généré automatiquement. Vous pouvez le personnaliser.</span>
        )}
      </div>

      {extraFields.map(([key, label, inputType, required]) => (
        <div className="form-group" key={key}>
          <label>{label} {required && <span className="req">*</span>}</label>
          <input
            required={required}
            type={inputType || "text"}
            placeholder={label}
            value={extras[key] || ""}
            onChange={(e) => setExtras({ ...extras, [key]: e.target.value })}
          />
        </div>
      ))}

      {doctors && <div className="form-group"><label>Docteur(s) référent(s) <span className="req">*</span></label><select required multiple value={extras.doctors || []} onChange={selectDoctors}>{doctors.map((doctor) => <option key={doctor._id} value={doctor._id}>{doctor.firstName} {doctor.lastName}</option>)}</select><span className="code-hint">Maintenez Ctrl/Cmd pour sélectionner plusieurs docteurs.</span></div>}

      <button className="primary wide" disabled={loading || !codeGen.code}>
        {loading ? "Enregistrement..." : "Enregistrer"}
      </button>
    </form>
  );
}

/* ──────────────────────────────────────────────
   Resource card
   ────────────────────────────────────────────── */
function Resource({ title, icon: Icon, items, render, onDelete }) {
  return (
    <section className="card resource premium-card">
      <div className="resource-header">
        <div className="resource-icon"><Icon size={18}/></div>
        <h2>{title}</h2>
      </div>
      <div className="resource-list">
        {items.map((item) => (
          <div key={item._id} className="resource-item">
            <div className="resource-item-content">{render(item)}</div>
            <button className="delete-btn" onClick={() => onDelete(item._id)} title="Supprimer"><Trash2 size={15} /></button>
          </div>
        ))}
        {!items.length && <p className="muted empty-state">Aucun élément.</p>}
      </div>
    </section>
  );
}

/* ──────────────────────────────────────────────
   UserForm
   ────────────────────────────────────────────── */
function UserForm({ levels, onSubmit, loading }) {
  const [data, setData] = useState(initialUser);
  return (
    <form className="dynamic-form" onSubmit={(e) => { e.preventDefault(); onSubmit({ ...data, level: data.level || undefined }); setData(initialUser); }}>
      <div className="two-fields">
        <div className="form-group"><label>Prénom <span className="req">*</span></label><input required placeholder="Prénom" value={data.firstName} onChange={(e) => setData({ ...data, firstName: e.target.value })} /></div>
        <div className="form-group"><label>Nom <span className="req">*</span></label><input required placeholder="Nom" value={data.lastName} onChange={(e) => setData({ ...data, lastName: e.target.value })} /></div>
      </div>
      <div className="form-group"><label>E-mail <span className="req">*</span></label><input required type="email" placeholder="E-mail" value={data.email} onChange={(e) => setData({ ...data, email: e.target.value })} /></div>
      <div className="form-group"><label>Téléphone</label><input placeholder="Téléphone" value={data.phone} onChange={(e) => setData({ ...data, phone: e.target.value })} /></div>
      <div className="form-group">
        <label>Rôle <span className="req">*</span></label>
        <select value={data.role} onChange={(e) => setData({ ...data, role: e.target.value })}>
          <option value="student">Étudiant</option><option value="level_admin">Responsable de niveau</option>
          <option value="local_doctor">Docteur local</option><option value="contract_doctor">Docteur vacataire</option>
        </select>
      </div>
      <div className="form-group">
        <label>Niveau (Optionnel)</label>
        <select value={data.level} onChange={(e) => setData({ ...data, level: e.target.value })}>
          <option value="">Sans niveau</option>
          {levels.map((x) => (<option key={x._id} value={x._id}>{x.name}</option>))}
        </select>
      </div>
      <div className="form-group"><label>Mot de passe provisoire <span className="req">*</span></label><input required minLength="12" type="password" placeholder="Minimum 12 caractères" value={data.password} onChange={(e) => setData({ ...data, password: e.target.value })} /></div>
      <button className="primary wide" disabled={loading}>
        {loading ? "Création..." : "Créer le compte"}
      </button>
    </form>
  );
}
